version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: kevin
      POSTGRES_PASSWORD: spiel12345
      POSTGRES_DB: monster_cards
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

